// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR-XlwdKQA8abfs9w1gweHGyA7U21XXRk',
    appId: '1:237119031938:android:d1dcfc1621752f94a5029b',
    messagingSenderId: '237119031938',
    projectId: 'stock-market-20b3b',
    databaseURL: 'https://stock-market-20b3b-default-rtdb.firebaseio.com',
    storageBucket: 'stock-market-20b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK9hPh-pJ7VMb8Yi9ZHmycGkKP5vydHgY',
    appId: '1:237119031938:ios:5167d0c7158d8a90a5029b',
    messagingSenderId: '237119031938',
    projectId: 'stock-market-20b3b',
    databaseURL: 'https://stock-market-20b3b-default-rtdb.firebaseio.com',
    storageBucket: 'stock-market-20b3b.firebasestorage.app',
    iosBundleId: 'com.stock.market.stockMarket',
  );
}
